### ISSUE TITLE
Could not find rubocop-rails-1.2.2 in any of the sources

### ISSUE THREAD

**Issue by melissamcewen** [CaravanTransit/Caravan-App#100]
## Detailed Description
Running `bundle install`
Get `Could not find rubocop-rails-1.2.2 in any of the sources`

Rubygems says it was yanked
https://rubygems.org/gems/rubocop-rails/versions

Project was apparently renamed??? Should be easy fix then https://github.com/toshimaru/rubocop-rails_config 😱

**Comment by vkoves** [comment]
Should be closed by the tagged pull request
