### ISSUE TITLE
Add Photo Support

### ISSUE THREAD

**Issue by vkoves** [CaravanTransit/Caravan-App#18]
Certain types of issues are best described with a picture, so allowing photo attachment to issues would be very useful.

**Comment by jannielung** [comment]
Caravan has decided against allowing photos as this will necessitate moderation.

**Comment by AcademyInPeril** [comment]
To expand just a little bit on reasoning:

Some platform moderation will likely be needed (deletion of false reports or spam, etc.), but adding photo capabilities opens the possibility of public shaming (especially of homelessness) in a fashion that we don't believe we're adequately equipped as a platform to moderate effectively.
