### ISSUE TITLE
Add Slack and GitHub Info to Breakout on ChiHackNight repository

### ISSUE THREAD

**Issue by CheersJBJ** [CaravanTransit/Caravan-App#28]

**Comment by AcademyInPeril** [comment]
@vkoves, proposing modifications/additions to our description for our issue on the ChiHackNight repo:

**About the group**
Transit Network is a platform that democratizes the flow of information about issues that riders encounter on public transit. Based on Ruby on Rails and open GTFS data, our team is building an app that can be adapted to thousands of train, bus, trolley, boat, and other types of transit lines around the world, allowing riders to tailor their trips based on reports from other users about cleanliness, delays, crime, and more. Transit Network seeks to empower transit users to better their experience and pressure transit administrators to address repetitive issues in a public, data-backed fashion, making all its data available to those seeking to push change forward at the local level.

We have a channel in the ChiHackNight Slack, #transit-network.

**Group leaders**
Add me please!

**Who we're looking for**
Ruby on Rails programmers, mapping and transit data enthusiasts, community outreach experts, and anybody who believes in what we're doing!

**Comment by CheersJBJ** [comment]
Sorry didn't make it tonight. Wife is in the hospital. Hoping to be there next week. Thanks...

**Comment by AcademyInPeril** [comment]
We won't be meeting tonight, but pay attention to the #transit-network channel in the ChiHackNight Slack for work that we'll be doing throughout the next week!

**Comment by vkoves** [comment]
@AcademyInPeril - the [CHN breakout group issue] has been updated. The GitHub link was already there, and the Slack channel is now included.
