### ISSUE TITLE
No Way to View Issues from Search or Line List

### ISSUE THREAD

**Issue by vkoves** [CaravanTransit/Caravan-App#33]
You can report issues by looking at a line and then hitting the plus on the issue, or by doing the same in search. However, you cannot view issues on a stop without favoriting it or being near the stop. You should probably be able to click the stop and see the issues for it.

**Comment by vkoves** [comment]
This should be resolved by PR #35, which adds an individual stop page.

**Comment by AcademyInPeril** [comment]
This will be covered by #73 and #74.
