### ISSUE TITLE
90%+ Coverage with Unit Tests

### ISSUE THREAD

**Issue by grant-rez** [CaravanTransit/Caravan-App#4]
Transit-Network is missing unit tests. Unit tests allow contributors to more rapidly develop and iterate because these tests allow them to test their code often in order to make sure they did not break anything. Database tests need to be made in order to verify data is read in correctly specifically. [Here](http://guides.rubyonrails.org/testing.html)  is a good document on how to write unit test for Ruby on Rails.  Remember to document your tests so that others know what each test is testing and add potential fixes where possible.

**Comment by morrme** [comment]
Will you be sticking with Minitest for this?

**Comment by vkoves** [comment]
@morrme - most likely. I find Minitest works pretty well, so unless there's a very specific reason not to use it for this project, we'll stick with it.

**Comment by vkoves** [comment]
I've started working on this on a new branch: [`adding-tests`](https://github.com/vkoves/Transit-Network/tree/adding-tests)

If you want to help out, feel free to add your work on that branch, or branch off of it and do a pull request back into it when you are ready.

**Comment by vkoves** [comment]
Closing, this was completed by the tagged PR. Here's proof:

![image](https://user-images.githubusercontent.com/3187531/41631417-1825ae7a-73fa-11e8-99d1-c7a1049d6a22.png)
