### ISSUE TITLE
All Lines are not sorted in any way other than Bus/Train

### ISSUE THREAD

**Issue by jazz580** [CaravanTransit/Caravan-App#40]
The "All Lines" page only differentiates between bus and train lines, with no other sorting. This means that the hundreds of buses have no particular ordering on the page, and makes browsing difficult and confusing. 
![all lines no sorting](https://user-images.githubusercontent.com/30378825/28853278-13032dda-76f5-11e7-94a1-3c2c021cd987.png)

**Comment by vkoves** [comment]
I think this is an issue that would be resolved by #42. @jazz580 - can I close this issue with the assumption that it will be resolved when #42 is implemented?
