### ISSUE TITLE
Make Favorite and Make Issue Buttons Further Apart

### ISSUE THREAD

**Issue by vkoves** [CaravanTransit/Caravan-App#46]
These buttons are too close together and are very small. Here's a screenshot:

![screenshot_825](https://user-images.githubusercontent.com/3187531/29304096-e3500664-8156-11e7-858d-f4129880ecfa.png)

Original report from UX review last week:
> The star/favorite button and the + button are too close together and too small (fat fingering is problematic) --> maybe put the star and + buttons on the row below the bus line

**Comment by AcademyInPeril** [comment]
This will be addressed in our general restyle covered by #73.
