### ISSUE TITLE
Fix Issues Page Not Being Mobile Friendly

### ISSUE THREAD

**Issue by vkoves** [CaravanTransit/Caravan-App#49]
The issues page does not work well on mobile, and should be fixed

Original report from UX review last week:
> The "Issues" page does not display well on an Android. The text does not wrap around and one must scroll to the right to see all the information. The alignment of the columns is also awkward.

**Comment by vkoves** [comment]
See my feedback on #45, in which I mention that I'm not sure this is supposed to be a publicly available page.

**Comment by AcademyInPeril** [comment]
The Issues page has been removed in its current form and will eventually reappear as originally intended under the admin panel (#72).
