### ISSUE TITLE
Local Copy: Home Page breaks due to Geokit Gem

### ISSUE THREAD

**Issue by rjaltman** [CaravanTransit/Caravan-App#5]
When running locally using development or test, SQLite is called upon for database management. However, this leads to problems with another gem in the project, Geokit, and the way it calculates distance within a one mile radius to nearby stops. Much like with other platforms that Geokit breaks on, the least() function is called when trying to complete this operation. However, since this method does not exist in SQLite (but does exist in MySQL2, and thus does not break on production), an error occurs on the majority of dashboard loads. Attached below is a screenshot at 360x640 resolution of the error's appearance. 

![image](https://cloud.githubusercontent.com/assets/3650044/23338353/430c545e-fbce-11e6-923b-e760ba9e2434.png)

**Comment by vkoves** [comment]
The documentation for GeoKit Rails seems to indicate this might be a problem. From there README:
> ## Database Compatability
>Geokit works with MySQL (tested with version 5.0.41), PostgreSQL (tested with version 8.2.6) and Microsoft SQL Server (tested with 2000).

However, SQLite seems to offer the functionality of the [least function](https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions075.htm) in the form of the [MIN function](http://www.sqlite.org/lang_corefunc.html#minoreunc) so it might be possible to modify the gem to use MIN for SQLite.

**Comment by rjaltman** [comment]
@vkoves, this sounds like a good approach. Just to be safe, I made sure the MySQL documentation lists the MIN function for use as well. I'll try and continue to spot any possible ignored ramifications involved in doing the substitution, but otherwise would approve this.

**Comment by vkoves** [comment]
I've opened an [issue on geokit-rails](https://github.com/geokit/geokit-rails/issues/120) for this that has specifics into what is going on via some research into the problem.
