### ISSUE TITLE
Add prominent login display for users who aren't logged in

### ISSUE THREAD

**Issue by jannielung** [CaravanTransit/Caravan-App#58]
Specify whether the user is signed in or not. Homepage needs to have a way for user to log in in order to view Favorites.

**Comment by vkoves** [comment]
@jannielung - log in is in the mobile menu, do you want it somewhere above or below the list of nearby stops?

**Comment by jannielung** [comment]
@vkoves It would be great to have it above the Search icon.

**Comment by vkoves** [comment]
@jannielung - why was this issue closed? It hasn't been completed

**Comment by jannielung** [comment]
@vkoves Please refer to the wireframes, Sign In Flow. Alternatively, we could please a Sign In button right below "Learn More" on the homepage.

https://www.figma.com/file/QNnIzW2XehQJULm4tLv4ABQo/Caravan_UX-Design-Drafts_Nadeen?node-id=195%3A0

**Comment by vkoves** [comment]
I'm closing this issue, as it'll be taken care of in #73, where the design has a "Sign In" page.
