### ISSUE TITLE
Sort nearest stops by distance

### ISSUE THREAD

**Issue by jannielung** [CaravanTransit/Caravan-App#60]
1) Add the distance from user to nearest stop
2) Sort the nearest stops by distance (closest to farthest)
3) Would be super cool if there was an option to visualize the stops on a map.

(Edit: The above are not considered primary issues/enhancements. The distance function is a helpful feature, but not essential. The issues listed below have much higher priority.)

**Comment by jannielung** [comment]
Actually, as I thought more about how I would use the app, it became clear to me that the homepage shouldn't display Nearest Stops (because that makes the user think that this is a transit stop/station finder-type app). Instead, the homepage should first display Nearest Issues/Incidents for both buses and trains (or all transit types). The user would then be able to click on either the bus or train lines that have the issues. That would be the most helpful functionally. The second purpose of this app is to report an issue. This function needs to be made more intuitive for the user. The + button isn't clear enough and its position on the screen isn't prominent enough. There should just be a button with the words "Report an Issue."

And maybe consider changing the name of the app to make it more clear what its purpose is.... maybe Transit Issues or something....

cc @vkoves

**Comment by vkoves** [comment]
My thought for how someone might use the app is that they are heading over to a train/bus station, click on the stop on the homepage, (or view the issues right there) see that there is a critical issue, and then go to a different nearby stop. Similarly, if I encounter an issue I would want to see stops near me so I can quickly find the stop I am at and report the problem. We might want to do a user story or something like that to diagram out how we expect/want people to use the app, as I think that'll help decide what we want to do on the homepage. 

Renaming the project is definitely something that we need to do, unfortunately we haven't been able to settle on any name.

**Comment by jannielung** [comment]
Maybe we should define use cases first? Or if you have already done so, please link to it here.

Personally, I would use this app to save me a trip to the bus or train station. I want to know the issue beforehand so I can save time and plan my trip better, head in a different direction, or plan not to use the CTA at all. The CTA website is a good way to get this info, but not on mobile. This is where your app comes in.

More broadly speaking, interviewing end users and understanding their needs/solving their problems is what drives UI - not the other way around. If you have time this week to talk in person about this, I'm happy to share what I know about product development.

**Comment by vkoves** [comment]
Definitely. Let's have a conversation next week at Chi Hack Night.

**Comment by AcademyInPeril** [comment]
This has been moved under #74.
