### ISSUE TITLE
Restyle Homepage to Prioritize Reporting

### ISSUE THREAD

**Issue by AcademyInPeril** [CaravanTransit/Caravan-App#73]
As discussed on 2/20, 2/26, and 2/27, orient the homepage around a vertical split: the top two thirds of the page will include a display of recent issues, and the bottom third will display a prompt to create a new issue report.

More detailed guidance on this is pending further UI/UX prototyping and discussion, but it is part of the MVP.

**Comment by vkoves** [comment]
Here is the final design:
![screenshot from 2018-07-31 20-16-36](https://user-images.githubusercontent.com/3187531/43495665-ef2d68ac-94fe-11e8-85a5-c4cf2fa6c99f.png)

**Comment by jannielung** [comment]
*The Caravan banner and the buttons should be the same shade of blue.
